defaults: &default
  encoding: UTF8
  adapter: postgresql
  pool: 30
  reaping_frequency: 10
  host: <%= Rails.application.secrets[:database][:host] %>
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>

development: *default

test:
  <<: *default
  database: test1-test

production: *default

staging: *default
